### ISSUE TITLE
Some search results do not show any text.

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#104]
1 go to http://chicago.councilmatic.org/search/?q=%22use+of+force%22
2. scroll down

**Comment by derekeder** [comment]
@fgregg "I think if we just reindex this, it should get sorted out"

**Comment by fgregg** [comment]
This seems to have something to do with very long pdfs. Rebuilding the index does not solve this, btw.

**Comment by derekeder** [comment]
this seems to be resolved now
