### ISSUE TITLE
reset button doesn't display after search on council members page

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#115]
Reset button should show up after I submit an address search:

<img width="1269" alt="screen shot 2016-02-01 at 10 30 01 am" src="https://cloud.githubusercontent.com/assets/919583/12723531/71528a1e-c8cf-11e5-8e34-10700098c8b7.png">

**Comment by cathydeng** [comment]
fixed via https://github.com/datamade/django-councilmatic/commit/93f3cc767bd3277884d69f5e91de444e9c672158
