### ISSUE TITLE
More descriptive loaddata output

### ISSUE THREAD

**Issue by patcon** [datamade/chi-councilmatic#118]
Seems the loaddata command is going to take me about an hour on my connection. Would be great if right from the get-go, we polled the counts of each type via API, and printed how many of each. Assuming we're hitting one per-second (which seems to be what I'm getting throttled at), we could offer an estimate of how long it will take to import data, or perhaps just show progress (ie. row count in db tables vs the count the API gives).

Might also be helpful to provide output informing user of whether process is incremental or not, so they know whether cancelling will lose all progress.

Anyhow, just mentioning these things that would improve my experience as a first-time developer. The experience is pretty flawless otherwise! :)

**Comment by cathydeng** [comment]
yeah that's useful feedback, we don't say anywhere in the documentation that loaddata takes a while. i'm moving this to an issue in django-councilmatic, since that's where loaddata code lives

**Comment by patcon** [comment]
Ah oops. Could've sworn I was in that repo when I posted. Thanks!
