### ISSUE TITLE
Time Zone Issues

### ISSUE THREAD

**Issue by wordyallen** [datamade/chi-councilmatic#119]
I'm getting all sort of errors and warnings, with respect to timezones...

does anyone have advice on getting the time zones to work?

I'm going to read through this: https://docs.djangoproject.com/en/1.9/topics/i18n/timezones/

**Comment by cathydeng** [comment]
where are you getting the errors/warnings? is it when loading data? if so, it's a warning & it's something we haven't addressed, but django does still do the right thing when loading it in. also the relevant code for that is in django-councilmatic, not chi-councilmatic.

are you getting errors elsewhere?

**Comment by wordyallen** [comment]
I let loaddata run for a few hours. I get the same error, whether I run loaddata or not.  

I'm using the default ubuntu box from digtial ocean. [Here](https://www.dropbox.com/s/mchw2wirfeygu9a/creating_chi_councilmatic_instance.txt?dl=0) is my set up for reference. 

When I  hit runserver:
```
/root/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/django/db/models/fields/__init__.py:1474:  RuntimeWarning: DateTimeField Event.start_time received a naive datetime (2016-02-04 11:55:13.363275) while time zone support is active.
```

When I look at the debugger I get : 
```
'NoneType' object has no attribute 'start_time'
```

Which calls `most_recent_past_city_council_meeting()`, which has `.filter(start_time__lt=datetime.now())`

I tried using timezone.now(),  setting USE_TZ to False, and changing postgres settings to 
`ALTER ROLE user SET timezone TO 'UTC';`



http://stackoverflow.com/questions/18622007/runtimewarning-datetimefield-received-a-naive-datetime

**Comment by cathydeng** [comment]
ok, these seem like two separate issues. the `'NoneType' object has not attribute 'start_time'` suggests that there isn't a most recent past city council meeting, which likely isn't a timezone issue. did loaddata complete? if you look in the event table (`councilmatic_core_event`) do you see anything? 

by the way, what are you trying to do? are you trying to contribute to chi-councilmatic? adapt it to another city?

**Comment by wordyallen** [comment]
I'm trying to adapt. I'm working with Ernie for the miami version.  Loaddata has no been run in my current version. I'll run it and get back to you.

**Comment by fgregg** [comment]
@wordyallen, you may also want to join this slack channel, where we have a room for discussing councilmatic https://ocd-slack-invite-automation.herokuapp.com/

**Comment by cathydeng** [comment]
@wordyallen oh ok awesome! yeah, data needs to be populated before running the app
