### ISSUE TITLE
toggling between http and https in redirects

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#125]
When someone requests an old councilmatic url like:

http://chicagocouncilmatic.org/legislation/1824826

it takes six redirects to get it to 

https://chicago.councilmatic.org/legislation/o-2014-5685/

because the redirects are toggling between http and https

![screenshot from 2016-02-17 15 31 00](https://cloud.githubusercontent.com/assets/536941/13125555/c9378fe0-d58b-11e5-8872-11bc36bb81d9.png)

**Comment by fgregg** [comment]
This is killing all our page rank, because the google bot will only follow three redirects

**Comment by fgregg** [comment]
This looks relevant. Attn @evz @derekeder 

http://stackoverflow.com/questions/8153875/how-to-deploy-an-https-only-site-with-django-nginx

**Comment by derekeder** [comment]
We are now :)

On Wed, Feb 17, 2016 at 3:48 PM, Forest Gregg <notifications@github.com>
wrote:

> are we directly redirecting *http*://chicagocouncilmatic.org to *https*://
> chicago.councilmatic.org?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/chi-councilmatic/issues/125#issuecomment-185422942>
> .
>



-- 
Derek Eder
@derekeder <https://twitter.com/#!/derekeder>
derek.eder@gmail.com
derekeder.com

**Comment by evz** [comment]
Another way to think about this is to just point all of the domains at the IP (instead of doing a DNS redirect) and then setup a virtual host in Nginx to handle all of them. That's one less redirect, at least.

**Comment by fgregg** [comment]
http://security.stackexchange.com/questions/8964/trying-to-make-a-django-based-site-use-https-only-not-sure-if-its-secure

**Comment by fgregg** [comment]
This is still a problem, @evz:

```bash
> curl -s -I http://chicago.councilmatic.org/legislation/1634031
HTTP/1.1 301 Moved Permanently
Server: nginx/1.8.0
Date: Fri, 11 Mar 2016 14:15:21 GMT
Content-Type: text/html
Content-Length: 184
Connection: keep-alive
Location: https://chicago.councilmatic.org/legislation/1634031

> fgregg@thinkpenguin:~/public/dedupe$ curl -s -I https://chicago.councilmatic.org/legislation/1634031
HTTP/1.1 301 MOVED PERMANENTLY
Server: nginx/1.8.0
Date: Fri, 11 Mar 2016 14:17:44 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Location: http://chicago.councilmatic.org/legislation/o-2014-145/
Strict-Transport-Security: max-age=31536000

 > curl -s -I http://chicago.councilmatic.org/legislation/o-2014-145/
HTTP/1.1 301 Moved Permanently
Server: nginx/1.8.0
Date: Fri, 11 Mar 2016 14:18:41 GMT
Content-Type: text/html
Content-Length: 184
Connection: keep-alive
Location: https://chicago.councilmatic.org/legislation/o-2014-145/
```

**Comment by fgregg** [comment]
+1

**Comment by fgregg** [comment]
:+1:

**Comment by fgregg** [comment]
we are down to two redirects
