### ISSUE TITLE
Ability to remove selected filters from search

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#129]
On the search page, we have one button for clearing all filters 

<img width="409" alt="screen shot 2016-02-24 at 1 39 04 pm" src="https://cloud.githubusercontent.com/assets/919583/13298343/04f1974a-dafc-11e5-9ee7-9235a7a40ccf.png">

Let's instead add the ability to 'x' a selected filter from the list to remove it.

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/6d81da28435a31eff1e7f35662515a20aa935417
