### ISSUE TITLE
bill ids not showing up in google

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#135]
It's pretty bad.

Searching for 'O2016-2699' yields no Councilmatic results, though City Hall Monitor does show up: https://www.google.com/search?q=O2016-2699&ie=utf-8&oe=utf-8

Even searching for 'O2016-2699 Chicago Councilmatic' does not return the right ordinance on the first page: https://www.google.com/search?q=O2016-2699&ie=utf-8&oe=utf-8#safe=off&q=O2016-2699+chicago+councilmatic

Why is that?

**Comment by derekeder** [comment]
Also, not a good sign that our index of pages on google is going down: 

<img width="502" alt="screen shot 2016-05-07 at 4 15 51 pm" src="https://cloud.githubusercontent.com/assets/919583/15094602/0759c442-146f-11e6-8c13-3184fe33da8f.png">

**Comment by fgregg** [comment]
The phrase "O2016-2699" does not appear on
https://chicago.councilmatic.org/legislation/o-2016-2699/

**Comment by derekeder** [comment]
True, and searching for 'Ordinance 2016-2699' does return 3 councilmatic results: https://www.google.com/search?q=Ordinance+2016-2699&ie=utf-8&oe=utf-8

It may be worth including the official name of the ordinance **if** people are searching for them that way

**Comment by fgregg** [comment]
I doubt that many people are.

**Comment by fgregg** [comment]
I think marking things up as creative work could be a good way to go: https://schema.org/CreativeWork

They have alternate titles.

**Comment by cathydeng** [comment]
we also encountered some other identifier issues (leading zeroes, spaces) when working on councilmatic search for bills. made a bunch of alternate identifiers here:
https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templatetags/extras.py#L96-L100

the search term works on chicago councilmatic search. currently the name iterations only live in the bill index; we should add them in the page markup as well

**Comment by derekeder** [comment]
This continues to be a problem:

<img width="1012" alt="screen shot 2016-07-16 at 3 42 16 pm" src="https://cloud.githubusercontent.com/assets/919583/16897064/ff3a9956-4b6b-11e6-81e1-f0abed7f992c.png">

I think there is something strange still going on with our HTTP response codes. Fetching any page from Google returns a 301 response:

<img width="622" alt="screen shot 2016-07-16 at 3 41 59 pm" src="https://cloud.githubusercontent.com/assets/919583/16897071/1e5afe5c-4b6c-11e6-86d9-f528531de058.png">

We need to look into this.

**Comment by fgregg** [comment]
that's what should happen (you are redirecting a http to a https)

**Comment by fgregg** [comment]
I don't know why the index is declining though

**Comment by fgregg** [comment]
i think we might want to see what the webmaster  analytics looks like for https://chicago.councilmatic.org (i think that webmaster tools might treat that as a distinct from http://chicago.councilmatic.org)

**Comment by derekeder** [comment]
ok to change from http to https you have to make a new site in webmaster tools. I just did and deleted the old one

**Comment by derekeder** [comment]
Let's give this a few weeks and see how it goes

**Comment by fgregg** [comment]
these queries are working now
