### ISSUE TITLE
4th ward alderman is out of date

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#137]
Will Burns is still listed as the 4th Ward Alderman: https://chicago.councilmatic.org/person/burns-william-d/

His seat was vacated and he was replaced by Sophia King in April: https://chicago.councilmatic.org/legislation/a-2016-43/

The Chicago Legistar site is showing the correct info: https://chicago.legistar.com/PersonDetail.aspx?ID=167474&GUID=9F0CDCDE-8C1F-4D72-8EA2-84D90275B3DB&Search=

**Comment by cathydeng** [comment]
info isn't updated on the ocd api (missing end dates to membership posts)

relevant url: http://ocd.datamade.us/ocd-organization/ef168607-9135-4177-ad8e-c1f7a4806c3a/
relevant post id: `ocd-post/ddb573d8-0116-44f6-83fa-1d2d7da3e1cf`
