### ISSUE TITLE
Show joint meetings on individual committee page

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#142]
For example, there was a Joint Committee Meeting of Budget and Government Operations; Public Safety on the 7/7/2016. https://chicago.councilmatic.org/event/494284/

On the committee pages for Budget this meeting does not show up https://chicago.councilmatic.org/committee/committee-on-budget-and-government-operations/

**Comment by fgregg** [comment]
Recent legislative action of joint committees should also show up on individual committee pages.

**Comment by derekeder** [comment]
i think this is no longer an issue
