### ISSUE TITLE
Former alderman Burns is listed as member of Committee for Rules

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#144]
https://chicago.councilmatic.org/committee/committee-on-committees-rules-and-ethics/

**Comment by fgregg** [comment]
The OCD data now has data for the terms of committee memberships. We should filter these views by *current* committee members.

**Comment by fgregg** [comment]
Since this is something that will come up in all councilmatics, it should probably be fixed in django councilmatic. I'll assign regina.

**Comment by reginafcompton** [comment]
Fixed!
