### ISSUE TITLE
Widgets are not showing updated information

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#146]
Compare https://chicago.councilmatic.org/legislation/o-2016-4792/widget/ to https://chicago.councilmatic.org/legislation/o-2016-4792/

The widget is showing out of date information. 

This is a pretty big bug. We should figure this one out.

**Comment by cathydeng** [comment]
what information is out of date? ...the pages look the same to me?

**Comment by fgregg** [comment]
oops! sorry this was my local cache.
