### ISSUE TITLE
Ordinance tag pages should publish RSS feeds

### ISSUE THREAD

**Issue by stevevance** [datamade/chi-councilmatic#154]
At the [Latin@ Techies hackathon](http://latinotechies.com/2016/11/12/join-us-for-the-latin-hackathon-team-presentations/) on Saturday, Nov 12, one group was interested in creating an alert system for proposed zoning changes. Before they could do that they would have to know who is proposing zoning changes, where, and when. 

Sometimes alders publicize public meetings about a zoning change, but no zoning change is required to have a public deliberation, and therefore many times alders make zoning change without any public awareness. 

I showed this group that you can see a list of proposed zoning changes on Chicago Councilmatic, and that they probably wouldn't have to scrape for the data because CC provides RSS feeds in many places. 

Tag pages, like [this one for zoning reclassification](https://chicago.councilmatic.org/search/?q=&selected_facets=topics_exact:Zoning%20Reclassification), however, don't appear to publish RSS feeds – but they should!

**Comment by derekeder** [comment]
Actually, it does! https://chicago.councilmatic.org/search/rss/?q=&selected_facets=topics_exact:Zoning%20Reclassification

We just aren't showing a link to the RSS feed when there is no search term provided. Filing a new UI issue for this!
