### ISSUE TITLE
An event appears twice

### ISSUE THREAD

**Issue by stevevance** [datamade/chi-councilmatic#155]
<img width="777" alt="screenshot 2016-11-15 10 52 07" src="https://cloud.githubusercontent.com/assets/1330459/20314929/a007caba-ab21-11e6-91e0-9b70fa1cec10.png">

Seen on https://chicago.councilmatic.org/events/

1st event goes to https://chicago.councilmatic.org/event/ocd-event/d66c26b6-48b5-4e26-a147-29556136d7c4/ (which is 404)

2nd event goes to https://chicago.councilmatic.org/event/508666/

**Comment by fgregg** [comment]
This type of error has been resolved.
