### ISSUE TITLE
rss feed for events

### ISSUE THREAD

**Issue by codersquid** [datamade/chi-councilmatic#157]
I would enjoy an rss feed for upcoming events. How easy would that be to add?

**Comment by derekeder** [comment]
@codersquid glad you asked! 

We just launched RSS & email alerts for [NYC Councilmatic](https://nyc.councilmatic.org/). We’ll be bringing them to Chicago soon.

https://medium.com/@ppolitics/get-email-alerts-for-nyc-council-22c5f3e6234
