### ISSUE TITLE
Redirects for people and events

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#169]
Now that we are adding hashes to the slugs for people and events, we need to set up redirects for these. 

@evz, how do you feel about *not* adding hashes for bills. We haven't had a problem with dupes of bill ids in nyc or chicago?

**Comment by evz** [comment]
True. I think we're already committed for NYC. How do you suggest we go back on that for Chicago given that the `import_data` script now adds those to the slugs? @reginafcompton was able to [write some tests](https://github.com/datamade/nyc-councilmatic/blob/master/nyc/tests/tests.py#L7) for NYC that ensure that everything that was in there when we started redirects properly. [The code](https://github.com/datamade/nyc-councilmatic/blob/master/nyc/views.py#L25) that actually does the redirecting is pretty light, too.

**Comment by reginafcompton** [comment]
This seems like a "six of one, half of dozen of the other" situation.....the redirect for the NYC Bills will still work, even if we revert back to the hash-less slugs (it uses the "startswith" filter, so it will catch what it should).....but, as @evz notes, the code for all this is pretty lightweight. I am fine either way, and I can happily implement the redirect and testing for Chicago, too. 

As long as we make a decision before the launch of LA Metro...to avoid triplicating this problem.

**Comment by fgregg** [comment]
I think we should do hashless urls for bills.

**Comment by reginafcompton** [comment]
What is the status on this issue? Hashless bills, right?
