### ISSUE TITLE
Error on legislation PDF

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#184]
Error loading the PDF on this interesting piece of legislation: https://chicago.councilmatic.org/legislation/r-2014-641/

**Comment by fgregg** [comment]
loads for me. could you screenshot?

**Comment by derekeder** [comment]
'unexpected server response'

<img width="760" alt="screen shot 2017-02-27 at 11 56 59 pm" src="https://cloud.githubusercontent.com/assets/919583/23393448/848b457c-fd48-11e6-96c4-e34457232d3b.png">

**Comment by derekeder** [comment]
Lol - privacy badger strikes again! Please disregard

<img width="424" alt="screen shot 2017-02-27 at 11 58 34 pm" src="https://cloud.githubusercontent.com/assets/919583/23393483/bb89e132-fd48-11e6-9072-48446b359e37.png">

**Comment by fgregg** [comment]
What is it hat is making privacy badger angry?

**Comment by derekeder** [comment]
It just has an overly aggressive block list.
