### ISSUE TITLE
Some RSS feeds aren't working

### ISSUE THREAD

**Issue by stevevance** [datamade/chi-councilmatic#188]
I'm seeing that some RSS feeds are working (legislation specific), but not others (the search-based ones).
Works: https://chicago.councilmatic.org/legislation/o-2017-150/rss/
Doesn't work: https://chicago.councilmatic.org/search/rss/?&selected_facets=topics:Land%20Use (I get the "Internal server error" page)

Forest asked me to tag @reginafcompton

**Comment by stevevance** [comment]
I'm getting the 502 bad gateway error now

**Comment by fgregg** [comment]
yeah have an issue for that #189
