### ISSUE TITLE
RSS feeds for large search facets timeout

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#189]
The feed for large facets, like this one https://chicago.councilmatic.org/search/rss/?&selected_facets=topics:Land%20Use

time out. 

Smaller facets work, like https://chicago.councilmatic.org/search/rss/?&selected_facets=topics:Municipal%20Code works

What's probably going on is that we are trying to render **all** the results into the rss feed. We should just do the last 100.

**Comment by derekeder** [comment]
this is no longer an issue
