### ISSUE TITLE
Councilmatic API response has a lot of duplicates

### ISSUE THREAD

**Issue by stevevance** [datamade/chi-councilmatic#202]
[API call](http://ocd.datamade.us/bills/?title__icontains=Historical%20landmark%20designation&sort=-actions__date&from_organization=ocd-organization/ef168607-9135-4177-ad8e-c1f7a4806c3a) - do an in-browser find for "O 2017-109" and you'll see that that record appears three times. 

This happens in every API call I've tried (I call it four times daily, one each for a different topic).

**Comment by fgregg** [comment]
hrmm.. weird. it's all the same ocd identifier.

**Comment by derekeder** [comment]
we no longer support an API, so closing this issue
