### ISSUE TITLE
Alert message after creating an account

### ISSUE THREAD

**Issue by reginafcompton** [datamade/chi-councilmatic#205]
An alert message does not appear, after creating an account. We should see this:

<img width="1153" alt="screen shot 2017-05-26 at 2 00 31 pm" src="https://cloud.githubusercontent.com/assets/13078679/26512810/f083badc-422d-11e7-8545-2bc896d6a9b9.png">

**Comment by reginafcompton** [comment]
Take a look at the base.html file.

**Comment by derekeder** [comment]
removing notifications in #285, so we won't need to do this
