### ISSUE TITLE
Ald Santiago showing up twice on the rules committee

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#206]
https://chicago.councilmatic.org/committee/committee-on-committees-rules-and-ethics-d05d22b44a74/

<img width="800" alt="screen shot 2017-06-02 at 12 08 07 pm" src="https://cloud.githubusercontent.com/assets/919583/26736607/7317a9b4-478c-11e7-8929-d6e234e7ddc4.png">

**Comment by reginafcompton** [comment]
She's gone.

**Comment by derekeder** [comment]
😸
