### ISSUE TITLE
Fix sort-by options when accessing the facets via the tag

### ISSUE THREAD

**Issue by reginafcompton** [datamade/chi-councilmatic#211]
After clicking on a facet (as given in the bill tag), the sort by options do not work.

<img width="483" alt="screen shot 2017-06-21 at 8 57 58 am" src="https://user-images.githubusercontent.com/13078679/27387976-c3e61b1e-565f-11e7-8703-b7e224973cfa.png">

**Comment by derekeder** [comment]
this appears to be working again
