### ISSUE TITLE
Notifications emails are missing context

### ISSUE THREAD

**Issue by evz** [datamade/chi-councilmatic#216]
When you get an update about a bill that has been acted upon by a committee that you subscribe to, the only actions that are shown are the actions from that committee. So, for instance, there were a bunch of bills that we passed by city council yesterday and in the emails I got notified about all the bills that were ever acted upon by committees that I subscribed to, regardless of whether the most recent action (aka, being passed by city council) was taken by that committee. It seems like the expected behavior might be to just include all the actions on those bills instead of just the actions taken by that committee. Or, once the committee no longer controls the bill, stop including it in the emails? I think the former is what I'd expect. Thoughts @fgregg or @derekeder ?

**Comment by fgregg** [comment]
| Or, once the committee no longer controls the bill, stop including it in the emails?

Agree

**Comment by derekeder** [comment]
we're removing notifications in #285, so we can close this.
