### ISSUE TITLE
Missing legislation R2017-336

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#228]
Honorific Resolution for Chi Hack Night is up on Legistar: https://chicago.legistar.com/LegislationDetail.aspx?ID=3026583&GUID=81A8CD54-3C2F-4F23-B996-DC7BB810C1E3&Options=Advanced&Search=

On Councilmatic, it does not show up in the following searches:

https://chicago.councilmatic.org/search/?selected_facets=sponsorships_exact%3APawar%2C+Ameya&selected_facets=topics_exact%3AHonorific+Resolution&sort_by=date&q=R2017-336

https://chicago.councilmatic.org/search/?selected_facets=sponsorships_exact:Pawar,%20Ameya&selected_facets=topics_exact%3AHonorific%20Resolution&_=1515090843884?&sort_by=date

**Comment by fgregg** [comment]
we got it now! https://chicago.councilmatic.org/legislation/r2017-336/
