### ISSUE TITLE
Overlapping cron + Councilmatic system

### ISSUE THREAD

**Issue by reginafcompton** [datamade/chi-councilmatic#231]
This morning, the Chicago data import caused numerous issues across the Councilmatic system:

```
OperationalError: FATAL: remaining connection slots are reserved for non-replication superuser connections
```

What was going on? 

`chicago-loaddata.log` indicates that the data import did not move past the "populating boundaries" step. Unwittingly, the cron continued to execute the import script, again and again and again. As a result, psql had too many connections open at the same time, and the other Councilmatics could not import data.

Some things to consider (working from lower to higher level):

- [x] `import_data` needs to hit the OCD API, which may not behave as expected. We should set timeout limits throughout the import script, which would cause the import to fail, but not freeze. [Here's where the script froze this morning](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/management/commands/import_data.py#L3052).

- [x] The Chicago cron does not use `flock` to prevent overlapping crontasks. Chicago, however, should not need `flock`, since the Chicago import does/should not take more then 15 minutes (whereas with NYC - that's a possibility). Let's determine a way to maintain these noisy failures - perhaps utilizing a messaging system in coordination with cron/flock, i.e., if flock cancels "x" number of tasks, then send DataMade a message?

- [ ] Isolate dependencies. If one Councilmatic hogs all the server resources, it should not affect the health of other Councilmatics.

**Comment by reginafcompton** [comment]
@fgregg - do you have other thoughts?

**Comment by fgregg** [comment]
superceded
