### ISSUE TITLE
This ordinance didn't load in the data from Legistar

### ISSUE THREAD

**Issue by stevevance** [datamade/chi-councilmatic#238]
https://chicago.councilmatic.org/legislation/o-2018-1903/
`o-2018-1903` seems to be a duplicate of `o-2018-1902`. 

1902 has the PDF
1903 doesn't have the PDF - instead it shows the following:
<img width="969" alt="screenshot 2018-03-27 13 21 51" src="https://user-images.githubusercontent.com/1330459/37986722-d465ab24-31c1-11e8-89ea-5f382c5a2c1a.png">

On 1903, the link "View on the Chicago City Clerk website" [goes to Legistar](https://chicago.legistar.com/LegislationDetail.aspx?ID=3359484&GUID=072375DC-9FE8-40AD-9C8F-70ADE71F77D1) but Legistar says "Invalid parameters!".

**Comment by fgregg** [comment]
1903 has been removed
