### ISSUE TITLE
Legislation hasn't been updated since the 6/12/19 council meeting

### ISSUE THREAD

**Issue by stevevance** [datamade/chi-councilmatic#255]
From Legistar:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/1330459/59886367-4428c700-9384-11e9-8db1-d27f709b21d7.png">

From Councilmatic:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/1330459/59886376-48ed7b00-9384-11e9-87ce-702d52e7ec4d.png">

**Comment by fgregg** [comment]
Updated!
