### ISSUE TITLE
Upgrade Chicago to Councilmatic 2.5

### ISSUE THREAD

**Issue by jeancochrane** [datamade/chi-councilmatic#257]
Steps to accomplish this:

### Publish Councilmatic 2.5

- [x] Pin LA Metro and NYC to Councilmatic <2.5
- [x] Publish `django-councilmatic` 2.5 to PyPi
- [X] Land https://github.com/datamade/django-councilmatic-notifications/pull/33
- [x] Publish `django-councilmatic-notifications` 2.5 to PyPi, either by setting up CI or doing it manually
- [x] Adjust https://github.com/datamade/chi-councilmatic/pull/252/files to use 2.5 versions of Councilmatic + Notifications and pull it in

### Create new Councilmatic 2.5 database

- [x] Create a new staging database for Chicago Councilmatic 2.5 on the Councilmatic server, `chicago_staging_2_5`
- [x] Make sure the new database reachable by the OCD API server
- [x] Initialize the new database by running Django Councilmatic migrations
- [x] From the OCD API server, initialize the DB for scraping using the `dbinit` command
- [x] Run a scrape into the Chicago Councilmatic DB from the OCD API server by setting the `DATABASE_URL` environment variable and calling the [appropriate commands](https://github.com/datamade/scrapers-us-municipal/blob/5fad26e9e451607427f1fa0ed0b1737693e2e12e/scripts/scrapers-us-municipal-crontask#L10-L13)
- [x] Confirm everything looks good on the Chicago Councilmatic staging site
- [x] Confirm that existing subscriptions will carry over and that folks will not be spammed when we switch
    - This might require writing a data migration for the Notifications app; not quite sure yet
- [x] Repeat the above steps for a Councilmatic 2.5 production database
- [x] Adjust the [scraper crontask](https://github.com/datamade/scrapers-us-municipal/blob/master/scripts/scrapers-us-municipal-crontask#L10-L13) to use the new `DATABASE_URL`
- [x] update google map api keys for staging and production

**Comment by jeancochrane** [comment]
Let me know if any of the above seems unexpected to you @fgregg!

**Comment by fgregg** [comment]
I would add one step at the beginning

1. Update LA Metro and NYC to use django-councilmatic<1.0

And I would the steps at the end.

1. Confirm that existing subscriptions will carry over and that folks will not be spammed when we switch

**Comment by jeancochrane** [comment]
Added, thanks!

**Comment by fgregg** [comment]
@derekeder I also need updated google map api keys for staging and production. we should also make it so that you are not the bottleneck for making those keys.

**Comment by derekeder** [comment]
@fgregg you and the DataMade team should have access to the API console with your DataMade Google account: https://console.developers.google.com

Can you confirm?

**Comment by derekeder** [comment]
Looks like images are not loading on the [Council Members page](https://chicago-staging.councilmatic.org/council-members/):

<img width="1273" alt="Screen Shot 2019-08-07 at 2 22 47 PM" src="https://user-images.githubusercontent.com/919583/62652053-0b3ab680-b920-11e9-8b56-8c96bd496cbb.png">

They do appear on the committee and aldermen detail pages:

<img width="868" alt="Screen Shot 2019-08-07 at 2 24 22 PM" src="https://user-images.githubusercontent.com/919583/62652083-1e4d8680-b920-11e9-9da6-af41b8e656e3.png">

This is not something that is happening on the live site: https://chicago.councilmatic.org/council-members/
