### ISSUE TITLE
502 error when sending test notification

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#258]
In doing QA for #257, I tried [sending myself a [test notification email](https://chicago-staging.councilmatic.org/account/subscriptions/):

<img width="1279" alt="Screen Shot 2019-08-07 at 2 55 32 PM" src="https://user-images.githubusercontent.com/919583/62653573-6de18180-b923-11e9-9f9b-2fbc86873129.png">

The server responds with a 502 error

**Comment by fgregg** [comment]
fixed it.
