### ISSUE TITLE
Google Maps previews are broken image links

### ISSUE THREAD

**Issue by jmithani** [datamade/chi-councilmatic#259]
I assume this is related to the new API restrictions.
Example: https://chicago.councilmatic.org/legislation/o2017-1023/

<img width="1062" alt="Screen Shot 2019-09-16 at 8 59 01 PM" src="https://user-images.githubusercontent.com/6961258/65005248-d75e9380-d8c4-11e9-963d-806a258b7302.png">

**Comment by hancush** [comment]
Still broken. :-(

**Comment by derekeder** [comment]
not seeing it on the original page, but am seeing this: https://chicago.councilmatic.org/legislation/o2018-7774/

it is likely due to not using an API key for Google, which is now required
