### ISSUE TITLE
Missing logo image

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#261]
The logo in the top left appears to not be loading:

<img width="1276" alt="Screen Shot 2019-09-26 at 1 35 51 PM" src="https://user-images.githubusercontent.com/919583/65715402-a4559600-e062-11e9-9369-fdbc59f96eae.png">

The path to the file appears to be incorrect:

<img width="442" alt="Screen Shot 2019-09-26 at 1 36 32 PM" src="https://user-images.githubusercontent.com/919583/65715430-b2a3b200-e062-11e9-91a2-6dda5d35a50f.png">

**Comment by fgregg** [comment]
this has been fixed
