### ISSUE TITLE
Missing legislation for last meeting on home page

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#262]
City Council did a lot more at the October 16th meeting than we are showing on the home page.

![Screenshot_2019-10-25 Chicago Councilmatic](https://user-images.githubusercontent.com/536941/67583828-5e035d80-f71a-11e9-8343-10a8d67280d0.png)

**Comment by stevevance** [comment]
No legislation introduced after 10/16/19 appears on the site.

**Comment by fgregg** [comment]
thanks, fixed!
