### ISSUE TITLE
Chicago legislation hasn't updated since Aug 21, 2020

### ISSUE THREAD

**Issue by tyo8** [datamade/chi-councilmatic#275]
Looking at the [Chicago Councilmatic site](https://chicago.councilmatic.org/search/?fbclid=IwAR3vT12kC36S5FRH3npVRvIgLvglkTN9rq2Fk3ZQklwQNNkagVPSGtjmLMY&selected_facets=bill_type_exact:resolution), it looks like Council Resolutions haven't updated since Aug 21, 2020 -- from looking through the closed issues, this looks to be the date at which a similar problem was fixed!

![image](https://user-images.githubusercontent.com/47438759/124200088-1958c980-da9a-11eb-9a22-f512176d0469.png)

With the exception of Committee Notices and Committee Agendas posted on 12/31/2020, it more broadly looks like no new legislation has been added to the site since September 09, 2020:

![image](https://user-images.githubusercontent.com/47438759/124200206-5cb33800-da9a-11eb-8d65-92915c3d31fc.png)

**Comment by hancush** [comment]
Thanks for prodding this, @tyo8! Fixed in #276.
