### ISSUE TITLE
Migrate app to Heroku

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#279]
- [ ] Get basic code deployed to heroku
- [ ] Dump and restore production db
- [ ]  Wire up elastic search (#278 )
- [ ] Figure out how to wire up scraper to database (either we have to let the scraper connect to a heroku database or maybe both would connect to an RDS database)
- [ ] Figure out how to schedule rebuilding the index

**Comment by hancush** [comment]
FWIW, here's how we prefer scheduling tasks on Heroku: https://github.com/datamade/how-to/blob/main/deployment/heroku/scheduling-tasks.md

**Comment by hancush** [comment]
Also for database, I think the most straightforward path is probably going to be scraping into a Heroku Postgres instance. We learned with CCFP that setting up a static IP to whitelist is possible, but not necessarily cheap, as it requires an add-on that charges per request and the Councilmatic app makes A LOT of requests. Pretty sure Heroku Postgres instances have stable URLs and creds we could plug into the scraper, but that'll need to be validated.

**Comment by derekeder** [comment]
closed via #280
