### ISSUE TITLE
Person Legistar links are incorrect

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#298]
Noticing that the Legistar links saved for people are incorrect. Here's a few examples:

Brian Hopkins: 
Saved link: https://chicago.legistar.com/PersonDetail.aspx?ID=355&GUID=DE9E2802-9FC2-420B-B8D7-905FB4940D94
Correct link: https://chicago.legistar.com/PersonDetail.aspx?ID=152674&GUID=C63D3709-94A9-4104-A076-931153CDC023

Anthony Beale:
Saved link: https://chicago.legistar.com/PersonDetail.aspx?ID=162&GUID=9D350EF8-54FB-4867-9110-A7CC0700F0DA
Correct link: https://chicago.legistar.com/PersonDetail.aspx?ID=60955&GUID=970F7168-7484-438F-A713-A90F0AE710E5

In all cases, the Legistar link displays `The page you requested was removed.`

**Comment by fgregg** [comment]
these should be fixed now.

**Comment by derekeder** [comment]
confirming they work now - nice!
