### ISSUE TITLE
add votes to legislation

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#300]
Once https://github.com/opencivicdata/scrapers-us-municipal/issues/372 comes in, we can add vote counts to the action table for each piece of legislation

We can access these values via:

If there's a vote event and there's not any `PersonVotes` its voice vote. 

- `Bill` => `Actions` => `VoteEvent` => `PersonVote` to get list of 50 yes/no/absent values for each member
- `Bill` => `Actions` => `VoteEvent` => `VoteCount` to get summary of vote counts

`VoteEvent.motion_text` and `VoteEvent.result` are should also be displayed

Models defined here:
https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/legislative/models/vote.py

**Comment by fgregg** [comment]
the vote counts are in the data is in the DB now.

**Comment by fgregg** [comment]
this query should give your split votes: `VoteEvent.objects.filter(counts__option='yes').filter(counts__option='no')`
