### ISSUE TITLE
duplicate committees

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#305]
Two committees are showing up twice in the list. The duplicates have identical slugs

[Aviation](https://chicago.councilmatic.org/committee/committee-on-aviation-67beb648a3f1/)
[Contracting Oversight and Equity](https://chicago.councilmatic.org/committee/committee-on-contracting-oversight-and-equity-c14ee5c77cad/)

**Comment by fgregg** [comment]
A couple of the memberships are recorded wrong in legistar. 

https://puddle.bunkum.us/chicago_council-c174bf8/membership?_sort=id&end_date__exact=2023-05-15

**Comment by fgregg** [comment]
no actually, it has to do with how we are handling the timezone naive record. http://webapi.legistar.com/v1/chicago/bodies/348/OfficeRecords

**Comment by fgregg** [comment]
No the problem is in the source data: http://webapi.legistar.com/v1/chicago/bodies/169/OfficeRecords

**Comment by fgregg** [comment]
We an also fix this by making this this query

https://github.com/datamade/django-councilmatic/blob/5b074f376667766e4b6dbf093871d294bb35fc51/councilmatic_core/models.py#L163-L167

ends with `distinct('organization_id') or something like that .
