### ISSUE TITLE
Ald Reilly has incorrect term start date

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#324]
42nd Ward Ald Reilly is listed as starting his term on May 29, 2019, which is incorrect:

https://chicago.councilmatic.org/person/reilly-brendan-1e50c314ab27/
![Screen Shot 2023-01-10 at 3 44 00 PM](https://user-images.githubusercontent.com/919583/211668662-295f7cfe-be93-4a80-b397-733ebdbee0ca.png)

He has been in office since 2007. @fgregg is this an error on the Clerk's side or with our scrapers?

**Comment by fgregg** [comment]
probably the clerks site, but if you open an issue for the scraper i’ll
take a look

**Comment by derekeder** [comment]
done. closing in favor of https://github.com/opencivicdata/scrapers-us-municipal/issues/376
