### ISSUE TITLE
preparing for upcoming 2023 legislative session

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#340]
A new legislative session will begin in May 2023. We should prepare this site to update when that happens.

As part of the annual redistricting process, there are new wards that will come into effect, which are up on the data portal: https://data.cityofchicago.org/Facilities-Geographic-Boundaries/Boundaries-Wards-2023-Map/cdf7-bgn3

@fgregg what needs to be updated on the scraper & data side?

**Comment by fgregg** [comment]
the scraper should do the right for alders and their posts.

the only thing we really need to change in the scraper is code that defines legislative sessions and code that assigns a bill to a legislative session

**Comment by hancush** [comment]
@derekeder Here's how to add the new legislative session to the scrapers: https://github.com/opencivicdata/scrapers-us-municipal/pull/279

**Comment by fgregg** [comment]
got the ward map updated this morning. @derekeder , i think the only thing left is images for the new alders?

**Comment by derekeder** [comment]
@fgregg nice! this page is pretty zippy now too https://chicago.councilmatic.org/council-members/

I can work on the images and alder details next in a new PR
