### ISSUE TITLE
switch from Legistar to chicityclerkelms.chicago.gov

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#352]
The Chicago City Clerk is launching a new legislative management system to replace Legistar: https://chicityclerkelms.chicago.gov/

Some time later today (June 16), the chicago.legistar.com/ will no longer work and we will need to update our scrapers to pull data from the new API. Documentation is here: https://api.chicityclerkelms.chicago.gov/

I've been told the new system will have all the same data as the old one. As of this writing, data is updated through June 2, 2023.

- [x] parse location for cancelled status

**Comment by fgregg** [comment]
taking some notes here:

## events
1. in the agenda items, there is no flag that indicates whether an item has votes associated with it, this means i have to check a separate url for every agenda item. the API should offer a flag.
2. the location field of events is being used to capture the status of events (i.e. cancelled) this should be moved to separate field

**Comment by fgregg** [comment]
the body doing the action is often wrong:

https://chicityclerkelms.chicago.gov/Matter/?matterId=6FBDB317-5C09-EE11-8F6D-001DD809B965

**Comment by stevevance** [comment]
It appears that `title` field in the Matters is not a filterable field. 
This is useful to me because I only want to extract matters pertaining to certain categories, i.e. "zoning reclassification" for zoning map amendments (rezonings). 

<img width="1466" alt="Screenshot 2023-07-17 at 16 28 19" src="https://github.com/datamade/chi-councilmatic/assets/1330459/48cb2959-027d-44e4-810e-81845b087e52">

**Comment by fgregg** [comment]
around 700 bills have an action where the org name is missing.
[missing_action_org.txt](https://github.com/datamade/chi-councilmatic/files/12126744/missing_action_org.txt)

**Comment by fgregg** [comment]
the https://chicityclerkelms.chicago.gov/Matter/?recordNumber= and https://api.chicityclerkelms.chicago.gov/matter/recordNumber= 

endpoints sometimes need a whitespace character after the record number, and sometimes not.

https://chicityclerkelms.chicago.gov/Matter/?recordNumber=O2023-0002003

doesn't work but

https://chicityclerkelms.chicago.gov/Matter/?recordNumber=O2023-0002003%20

does

**Comment by fgregg** [comment]
the new system has cases where there are multiple distinct entries for the same bill

https://chicityclerkelms.chicago.gov/Matter/?matterId=60659CA3-1F11-EE11-8F6C-001DD8094692
https://chicityclerkelms.chicago.gov/Matter/?matterId=27585215-4305-EE11-8F6D-001DD806EC60

https://chicityclerkelms.chicago.gov/Matter/?matterId=78E9D319-4D14-EE11-8F6D-001DD806F88B
https://chicityclerkelms.chicago.gov/Matter/?matterId=D47CEE41-4E14-EE11-8F6D-001DD806F9D9

**Comment by derekeder** [comment]
@fgregg we've been switched over for a while now. should we close and track data problems in separate issues?

https://notes.chicago.councilmatic.org/blog/using-data-from-new-system.html

**Comment by fgregg** [comment]
sure!
