### ISSUE TITLE
Something weird is happening with the votes for the approval of this bill

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#364]
https://chicago.councilmatic.org/legislation/a2023-0001255/

They are all showing as absent even though the matter was approved. This is how the data appears in the source system. https://chicityclerkelms.chicago.gov/Matter/?matterId=B4EE8A5F-5910-EE11-8F6C-001DD806D2E1#

might be how this is how they are representing voice votes?

**Comment by derekeder** [comment]
this is on the source system. we should notify them.

**Comment by fgregg** [comment]
notified the clerk's office.
