### ISSUE TITLE
missing name in this rollcall

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#365]
<img width="230" alt="Screenshot 2023-09-11 at 5 30 57 PM" src="https://github.com/datamade/chi-councilmatic/assets/536941/329affb8-9a21-441f-924a-dff59f87462b">

https://chicago.councilmatic.org/legislation/a2023-0001291/

**Comment by derekeder** [comment]
this is `Fuentes, Jessica L.`

the `L.` is new
