### ISSUE TITLE
500 error on event pages

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#371]
getting a 500 error on several chi councilmatic event pages, possibly due to a missing person or info:
sentry error: https://datamade.sentry.io/issues/4517638958/?project=63977&query=&referrer=project-issue-stream

examples:
* https://chicago.councilmatic.org/event/city-council-bec85f5dc371/
 https://chicago.councilmatic.org/event/city-council-0d9df6717dad/
* https://chicago.councilmatic.org/event/city-council-2b5b6dbf713c/

**Comment by fgregg** [comment]
there was a stray membership for lamont robinson that i failed to clean up. should be fixed now.
