### ISSUE TITLE
searching for "Fraternal Order of Police" did not return this CBA

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#382]
https://chicago.councilmatic.org/legislation/o2021-3449/

**Comment by derekeder** [comment]
our index seemed to be very out of date and also missing a lot of documents. running `rebuild_index` on it now. we will check next week to see if the `update_index` command worked as we expected

**Comment by derekeder** [comment]
great. reindexing is finished. let's check back on this next week to see if new items are getting added

![Screenshot 2023-10-27 at 8 55 33 AM](https://github.com/datamade/chi-councilmatic/assets/919583/ec005dff-4b7e-4142-b531-1c85130324d9)

**Comment by derekeder** [comment]
just checked the index and we are indeed adding bills to the index with our automated process

158,757 bills on Oct 27 => 159,018 bills on Nov 10

![Screenshot 2023-11-10 at 10 26 03 AM](https://github.com/datamade/chi-councilmatic/assets/919583/5848a4bf-b996-4960-ab27-5824f6175400)
