### ISSUE TITLE
this failed bill has the wrong status of active

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#383]
https://chicago.councilmatic.org/legislation/or2023-0002846/

**Comment by derekeder** [comment]
this bill has actions of 'Recommended to Pass' and 'Failed to Pass'. Our logic for `_terminal_status` looks at the entire history, not just the most recent one in the ordered list:

https://github.com/datamade/chi-councilmatic/blob/facd18fa3b1bcc35b013187bc7644bfe524524ea/chicago/models.py#L40-L55

My first thought would be to have it look at just the most recent status, but this would impact the status of all bills. @fgregg what's the safe fix here?

**Comment by fgregg** [comment]
this just looks like we never figured out what a failure would look like for an order, appointment, or resolution. let's pick this one up this friday.

**Comment by derekeder** [comment]
adding `order` to the list we check resolves this issue. is it possible for appointments or resolutions to fail?
