### ISSUE TITLE
link to non-routine bills in compare alderman page does not take you to a listing of non-routine bills *primarily* sponsored by the alder

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#387]
https://chicago.councilmatic.org/compare-council-members/

**Comment by derekeder** [comment]
yup - you're right. I don't think our search interface allows for searching for primary sponsors - just if they are on the list of sponsors. I wonder how difficult that would be to add.

**Comment by derekeder** [comment]
our plan is to change the search filter to only search for primary sponsors
