### ISSUE TITLE
"transfer tax" search does not return this bill

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#388]
[R2023-0004166](https://chicago.councilmatic.org/legislation/r2023-0004166/)

**Comment by derekeder** [comment]
confirming this: https://chicago.councilmatic.org/search/?q=%22transfer+tax%22&sort_by=date&order_by=desc

however searching for the ordinance number does work, so it is in the index: https://chicago.councilmatic.org/search/?sort_by=date&order_by=desc&q=R2023-0004166

seems like something to do with how the search is configured

**Comment by fgregg** [comment]
“garrit” also does not return https://chicago.councilmatic.org/legislation/or2023-0002846/

**Comment by derekeder** [comment]
we found a discrepancy between the search index and councilmatic's search results:

searching for "increase in Chicago real estate transfer tax rates" yields no results: https://chicago.councilmatic.org/search/?q=%22increase+in+Chicago+real+estate+transfer+tax+rates%22

but in the search index interface, we get the result we want: 

![Screenshot 2023-11-10 at 3 59 46 PM](https://github.com/datamade/chi-councilmatic/assets/919583/00e88ee3-3677-4e7d-b18b-2236ce51041b)

There is either a difference in what we are sending to elasticsearch or there may be some issue with matching up the bill objects to the results objects.

**Comment by derekeder** [comment]
here's the log we were able to get when searching for `"transfer tax"` locally:

[debug.log](https://github.com/datamade/chi-councilmatic/files/13924540/debug.log)

**Comment by derekeder** [comment]
excellent
