### ISSUE TITLE
Add OCRed text to full text search

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#40]
On legistar, they have the OCRed text of the bills available. THey are not very good, but probably are good enough to add to full text search. The data will soon be available in the scraper.

**Comment by fgregg** [comment]
I'm going to go ahead and do it.

**Comment by fgregg** [comment]
@cathydeng thoughts?

**Comment by cathydeng** [comment]
oh yeah - that'd be good for searching on

**Comment by fgregg** [comment]
k. this data is in the `extras` field, and called `ocr_full_text` 

There's data there now, but it's just the first page. In a few days, it should really be the full text. 

Is this something that's worth putting in the launch milestone?

**Comment by cathydeng** [comment]
ya, it's easy-ish to add

**Comment by fgregg** [comment]
we won't be displaying this text anywhere, the ocr is far from good enough for that.

**Comment by cathydeng** [comment]
yeah, I'll just add it to the text blob that search uses

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/46d2f71b28b5797f1edfeba505ad83292e54f403
