### ISSUE TITLE
Finish scraping full text of bills

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#42]
I've scraped 65K/76K bills. To wrap up the last 15% I need to

- Identify the full urls we have not scraped yet by finding the pages where have cache of the default version but not of the full text version. 
- Adapt the legistar scraper to accept a list of urls

**Comment by derekeder** [comment]
@fgregg is this done?

**Comment by fgregg** [comment]
No, there are 10K bills from 2010 that we don't have full text for.
Shouldn't be blocking, though, for the launch

On Fri, Jan 8, 2016 at 2:24 PM, Derek Eder <notifications@github.com> wrote:

> @fgregg <https://github.com/fgregg> is this done?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/chi-councilmatic/issues/42#issuecomment-170113906>
> .
>



-- 
773.888.2718

**Comment by derekeder** [comment]
ok, will remove from the milestone.
