### ISSUE TITLE
override django-councilmatic analytics code

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#44]
The Google analytics code is hard coded in django-councilmatic. This needs to be customizable for each instance

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/chi-councilmatic/commit/23bc99f69de74ac06993fee9ca7c18692fce55be & https://github.com/datamade/django-councilmatic/commit/9fc63520b89c15e007a44044a60b0d7fc5b809ee
