### ISSUE TITLE
add title to Rahm Emanuel

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#47]
We should probably indicate that Rahm Emanuel is the Mayor of Chicago.

http://chicouncilmatic.datamade.us/person/emanuel-rahm/

**Comment by fgregg** [comment]
Should also be added to committee members page

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/ca5a9ad24dcec1140169d504f0e5fa0da961bd81 & https://github.com/datamade/chi-councilmatic/commit/020868a742c74835cb75d202933ab0b245e547ac
