### ISSUE TITLE
Deal with subsitute ordinances

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#48]
The bill 

http://chicago.councilmatic.org/legislation/so-2015-6406/

has two versions, the orginal version and the substituted version that was passed. We wouldn't know that from looking at our page.

**Comment by fgregg** [comment]
This is a real bummer for important ordinances like the Inspector General ordinance bill https://chicago.councilmatic.org/legislation/so-2015-4229/

**Comment by derekeder** [comment]
Original bill: https://chicago.councilmatic.org/legislation/o-2015-4229/
Substitute bill: https://chicago.councilmatic.org/legislation/so-2015-4229/

Using the bill identifier, let's add a feature for showing related bills.

**Comment by fgregg** [comment]
Same thing for Claire's recycling bill

https://chicago.councilmatic.org/legislation/o-2016-4792/
https://chicago.councilmatic.org/legislation/so-2016-4792/

I have a couple of ideas, let me flesh them out today.

**Comment by fgregg** [comment]
Okay, Here's my proposal.

In the scraper, 

* SO2016-4792 will just show up as  alternate identifier for 02016-4792 (instead of as separate bill).
* on councilmatic, we will also, only have pages for the original ordinance
* we should 301 redirect /so-2016-4792 to /o-2016-4792
* we should add an "alternate identifiers" section to councilmatic bill detail pages. which will list, where approporiate the substituted ordinance identifier, this will also help with #135 

Thoughts @derekeder @cathydeng
