### ISSUE TITLE
In listing of recent legislative history on committee pages, give titles of bills.

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#53]
Just giving the bill identifier is not sufficient.

**Comment by cathydeng** [comment]
by title do you mean the description?

**Comment by fgregg** [comment]
I mean the field called title in OCD.

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/878063467362c131b52abfc8a719c40ae21d07be
