### ISSUE TITLE
better coloring for bill actions

### ISSUE THREAD

**Issue by cathydeng** [datamade/chi-councilmatic#57]
rn almost everything is blue. would be nice to have more colors indicating progress, hinderance, etc

bill actions have classifications. all the possible chicago classifications:

```
 passage
 failure
 committee-passage-unfavorable
 withdrawal
 committee-referral
 substitution
 filing
 committee-passage-favorable
 executive-signature

 committee-failure
 introduction
 amendment-passage
```

then we map the classifications to labels here: https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/models.py#L418-L434 (currently this is consistent across all councilmatics - should it be?)

then the labels get used in css classes: https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templates/councilmatic_core/legislation.html#L111

& then the color of these text color classes can live in chicago councilmatic css

**Comment by cathydeng** [comment]
turn blue to grey, since blue doesn't really mean anything. then the colors will be grey (default), green (moving forward) & red (moving backward)

perhaps have two shades of green, to differentiate between advancing towards to terminal status (e.g. recommended to pass) vs reaching terminal status (e.g. passed)?

**Comment by derekeder** [comment]
i think these colors are fine for now. closing.
