### ISSUE TITLE
on sponsor list on bill page, show ward of alderman at the time of bill (instead of current ward)

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#59]
http://chicago.councilmatic.org/legislation/o-2014-1511/

Does not show the wards of sponsoring alderman who are not current aldermen.

**Comment by derekeder** [comment]
this is working now
![Screen Shot 2023-01-11 at 10 25 19 AM](https://user-images.githubusercontent.com/919583/211860768-2fe20233-6c89-4b6e-86a6-31bb9b2ba527.png)
