### ISSUE TITLE
When we have more than three or four sponsors, may want to show the total number of sponsors

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#60]
Or have the sponsor list have a count.

http://chicouncilmatic.datamade.us/legislation/o-2014-1511/

The number of sponsors is a good indication that something has a chance of passing the council.

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/09e947e6f8bea63c3636ec4ae307a3ea5d36c5d3
