### ISSUE TITLE
We need image credits for all the images that we are using, unless the license does not require attribution

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#62]

**Comment by derekeder** [comment]
I'll take this on.

**Comment by fgregg** [comment]
We need to get licenses for almost all these images. Credit is not sufficient for these creative works.

**Comment by derekeder** [comment]
For future reference, the Chicago City Clerk website has black & white photos of all current aldermen: http://www.chicityclerk.com/city-council-news-central/council-members
