### ISSUE TITLE
Getting 502 bad gateway error when accessing a committee page

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#64]
http://chicouncilmatic.datamade.us/committee/committee-on-transportation-and-public-way/

All the other committe pages seem fine.

**Comment by cathydeng** [comment]
it looks like this is b/c they have lotsa bills & it takes too long to load. I'll limit the number of bills for a committee page

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/328e1c8b37dec69671ddc6a733d86a0ea626ceb5
