### ISSUE TITLE
change formatting of committee event listing

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#67]
![screenshot from 2016-01-11 17 20 54](https://cloud.githubusercontent.com/assets/536941/12249801/bea473e8-b887-11e5-894b-6128155b57cc.png)

The dates of these events should be left justified. Also, why are repeating the same title, which will always have the same title.

**Comment by derekeder** [comment]
Since the events have the same title, lets just rename the event title.

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/2edab888058c0373ed2e1e2389b94867d04251e0
