### ISSUE TITLE
search pagination does not retain filters

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#72]
To recreate, go here: http://chicouncilmatic.datamade.us/search/?q=&selected_facets=topics_exact:Residents

and then scroll down and navigate to the next page. Filters are not preserved

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/c4dec278e2644364e2ae1d2e1a86d1f1eca246be
