### ISSUE TITLE
duplicate events

### ISSUE THREAD

**Issue by cathydeng** [datamade/chi-councilmatic#74]
on committee pages, there seem to be lotsa duplicate events at the same date/time. an example:

A.
http://chicouncilmatic.datamade.us/event/440806/
ocd-event/0874f375-ff5f-4231-be88-5a8f43fff5f8 
https://chicago.legistar.com/MeetingDetail.aspx?ID=440806&GUID=D4D54B02-8E3C-431E-B89F-1A5DD6D4CFAB&Options=info&Search=

B.
http://chicouncilmatic.datamade.us/event/440815/
ocd-event/2e7d1865-fae2-4dc9-8e8e-488b4ce080c9 
https://chicago.legistar.com/MeetingDetail.aspx?ID=440815&GUID=2E472936-26A9-47AB-9CEF-540883363375&Options=info&Search=

C.
http://chicouncilmatic.datamade.us/event/ocd-event/ba445440-a604-4b75-b611-cff503174c14/
ocd-event/ba445440-a604-4b75-b611-cff503174c14 
https://chicago.legistar.com/MeetingDetail.aspx?ID=440806&GUID=D4D54B02-8E3C-431E-B89F-1A5DD6D4CFAB&Options=info&Search=

all are Committee on Budget and Government Operations, 10/09/15 9am (tho B has an agenda while A & C don't). all have unique ocd ids. A & C have same legistar source.

why??

**Comment by fgregg** [comment]
The duplication of A & C is a bug. I'll look into that.

A is normal meeting of the committee
B is a committee hearing

Committees often schedule hearings concurrently with their regular meetings.

**Comment by fgregg** [comment]
I may also be able to do a better job identifying hearings in the scraper, but legistar does not make it easy.

**Comment by cathydeng** [comment]
what's the diff between a meeting & a hearing? why do they take place at the same date & time for a committee?

**Comment by fgregg** [comment]
A regular meeting involves taking action on legislation. A hearing does
not. They are different types of events that sometimes are scheduled to
happen at the same time.

**Comment by fgregg** [comment]
The duplicate events was fixed by reloading the data.
