### ISSUE TITLE
I can't facet full text search

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#79]
1. go to http://chicouncilmatic.datamade.us/search/?q=%22inspector+general%22
2. Filter by active status. 

This goes to 
http://chicouncilmatic.datamade.us/search/?q=&quot;inspector%20general&quot;&selected_facets=inferred_status_exact:Active

Which returns no results

It should go to 

http://chicouncilmatic.datamade.us/search/?q=%22inspector%20general%22&selected_facets=inferred_status_exact:Active

Which returns the right result.

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/3669118860a3d61aa6d798007a61d2551bc7860e
