### ISSUE TITLE
Use right source

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#91]
Now that I'm scraping the bills from the API, I am putting the API url in the sources field in OCD. I am also putting in the legistar web url.

For " View on the Chicago City Clerk website " we need to go to the legistar url.

**Comment by cathydeng** [comment]
is this issue just for bills?

**Comment by fgregg** [comment]
yes.

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/6dffcaf6f10135d02e9ef8b7bb58e785a1256d2a
