### ISSUE TITLE
we should show current committee, like we used to.

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#93]
This very interesting order was referred to the committee on public safety

http://chicouncilmatic.datamade.us/legislation/or-2016-30/

but we don't show that info.

We could do this two ways.

1. Show the current controlling body (which we used to do)
2. Show the committee the bill was referred to.

I'm fine with either choice, but we should do one.

**Comment by cathydeng** [comment]
went with option 2 b/c 'controlling body' is confusing language, closed via https://github.com/datamade/django-councilmatic/commit/2369848dee0945c3b5d37dc405ea1bd76528a4ec

**Comment by fgregg** [comment]
I really like this solution. We should top-vertical align the history table. http://chicouncilmatic.datamade.us/legislation/o-2015-7406/
